server:
  port: 8085

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
          - id: user-service
            uri: lb://USERSERVICE
            predicates:
              - Path=/users/**
            filters:
              - StripPrefix=1



eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka